---
# role: jomrr.test
# file: molecule/all/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "meta/requirements.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
verifier:
  name: "ansible"
scenario:
  name: "all"
platforms:
  - name: almalinux-latest-test
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: alpine-latest-test
    image: "docker.io/jomrr/molecule-alpine:latest"
    pre_build_image: true
    override_command: false
  - name: debian-latest-test
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: fedora-latest-test
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-leap-latest-test
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-tumbleweed-latest-test
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: ubuntu-latest-test
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: true
