---
# role: jomrr.test
# file: .forgejo/workflows/dev-push-validate.yml

name: dev push validate

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: "${{ forgejo.workflow }}-${{ forgejo.ref }}"
  cancel-in-progress: true

jobs:
  molecule-default:
    name: Molecule ${{ matrix.name }}
    runs-on: podman
    timeout-minutes: 45

    strategy:
      fail-fast: true
      max-parallel: 8
      matrix:
        include:
          - name: test-almalinux-latest
            uns: jomrr
            img: almalinux
            tag: latest
          - name: test-alpine-latest
            uns: jomrr
            img: alpine
            tag: latest
          - name: test-debian-latest
            uns: jomrr
            img: debian
            tag: latest
          - name: test-fedora-latest
            uns: jomrr
            img: fedora
            tag: latest
          - name: test-opensuse-leap-latest
            uns: jomrr
            img: opensuse-leap
            tag: latest
          - name: test-opensuse-tumbleweed-latest
            uns: jomrr
            img: opensuse-tumbleweed
            tag: latest
          - name: test-ubuntu-latest
            uns: jomrr
            img: ubuntu
            tag: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Molecule default scenario
        run: |
          set -euo pipefail
          export uns="${{ matrix.uns }}"
          export img="${{ matrix.img }}"
          export tag="${{ matrix.tag }}"
          molecule test -s default
