---
# role: test
# file: tasks/main.yml

- name: TEST | Run demonstration tasks
  when: test_role_enabled
  block:
    - name: TEST | Load platform settings
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', __test_platform_files) }}"
      vars:
        __test_platform_files:
          files:
            - "{{ ansible_facts.os_family }}.yml"
          paths:
            - "{{ role_path }}/vars"

    - name: TEST | Demonstrate package management with an empty list
      become: true
      become_user: root
      ansible.builtin.package:
        name: "{{ __test_packages }}"
        state: present
