---
# role: test
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
      display_ok_hosts: false
      display_skipped_hosts: false
      show_task_path_on_failure: true
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        test_role_enabled: true
verifier:
  name: "ansible"
scenario:
  name: "dev"
platforms:
  - name: "almalinux-latest-test"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "alpine-latest-test"
    image: "docker.io/jomrr/molecule-alpine:latest"
    pre_build_image: true
    override_command: false
  - name: "debian-latest-test"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-test"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-test"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-test"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-test"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
